services:
  mysql:
    image: mysql:8.4
    container_name: neon-moon-mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "127.0.0.1:3306:3306"

    volumes:
      - neon_moon_mysql_data:/var/lib/mysql

volumes:
  neon_moon_mysql_data:
